gerrit:
  host: localhost
  port: 29418
  username: YourUserName
  git-config-email: "someemailaddress@somedomain.com"
  git-config-name: "some name"

groups:
  - name: group1
    owner: Administrators
    description: group1's description
  - name: group2
    owner: Administrators
    description: group2's description

users:
  - username: someOtherUser
    full-name: 'some other user'
    http-password: some password
    email: "someotheruser@somedomain.com"
    ssh-key: "ssh-rsa aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa ssh key comment"
    groups:
      - "group1"
      - "group2"

#projects:
#  - name: All-Projects
#    config: /etc/gerrit-pytho-tools/acls/All-Projects.config
#  - name: Project1
#    config: /etc/gerrit-python-tools/acls/Project1.config
#    source: git_repo_url
